int headers_consume (int length, char *buffer);
void headers_cleanup ();
int headers_compact ();
char *get_request (int part);
char *get_header (int header, int part);
int headers_is_error (int state);
int headers_get_state ();
char *headers_explain_state (int state);
int headers_has_version ();
int headers_has_request ();
